# Generated by Django 5.1.7 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive_id', models.CharField(max_length=100, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('web_view_link', models.URLField(blank=True, max_length=500, null=True)),
                ('web_content_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-modified_time'],
            },
        ),
    ]
